server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${SECRET_KEY}

security:
  jwt:
    secret-key: ${SECRET_KEY}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_ZONE_URL}
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        url: ${OTLP_METRICS_EXPORT_URL}
        step: 10s
    logging:
      endpoint: ${OTLP_LOGGING_EXPORT_URL}
    tracing:
      endpoint: ${OTLP_TRACING_EXPORT_URL}