server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/${AUTHENTICATION_DB}
    username: ${AUTHENTICATION_USER}
    password: ${AUTHENTICATION_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_ZONE_URL}
  instance:
    instance-id: ${spring.application.name}:${random.value}

security:
  jwt:
    secret-key: ${SECRET_KEY}

auth:
  service:
    client-id: ${AUTHENTICATION_SERVICE_CLIENT_ID}
    client-secret: ${AUTHENTICATION_SERVICE_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  otlp:
    metrics:
      export:
        url: ${OTLP_METRICS_EXPORT_URL}
        step: 10s
    logging:
      export:
        url: ${OTLP_LOGGING_EXPORT_URL}
        step: 10s