server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${CUSTOMERS_DB}
    username: ${CUSTOMERS_USER}
    password: ${CUSTOMERS_PASSWORD}
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${SECRET_KEY}

security:
  jwt:
    secret-key: ${SECRET_KEY}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_ZONE_URL}
  instance:
    instance-id: ${spring.application.name}:${random.value}

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

stripe:
  api-key: ${STRIPE_SECRET_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}
