server:
  port: 0

aws:
  localstack:
    region: ${AWS_REGION}
    endpoint: ${AWS_URI}
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

  production:
    region: ${AWS_REGION_PRODUCTION}
    access-key: ${AWS_ACCESS_KEY_PRODUCTION}
    secret-key: ${AWS_SECRET_KEY_PRODUCTION}

  s3:
    bucket: ${AWS_S3_BUCKET}

  sqs:
    queue:
      notify-subscription: ${NOTIFY_SUBSCRIPTION_QUEUE}
      notify-payment-approved: ${NOTIFY_PAYMENT_APPROVED}
      notify-payment-failed: ${NOTIFY_PAYMENT_FAILED}
      invoice-created: ${INVOICE_CREATED_QUEUE}

notification:
  sender-email: ${INTERNAL_SERVICE_EMAIL}

spring:
  cloud:
    aws:
      region:
        static: ${AWS_REGION}
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      sqs:
        endpoint: ${AWS_URI}

    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_ZONE_URL}
  instance:
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  otlp:
    metrics:
      export:
        url: ${OTLP_METRICS_EXPORT_URL}
        step: 10s
    logging:
      endpoint: ${OTLP_LOGGING_EXPORT_URL}