server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/${SUBSCRIPTION_DB}
    username: ${SUBSCRIPTION_USER}
    password: ${SUBSCRIPTION_PASSWORD}
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${SECRET_KEY}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_ZONE_URL}
  instance:
    instance-id: ${spring.application.name}:${random.value}

security:
  jwt:
    secret-key: ${SECRET_KEY}

aws:
  localstack:
    region: ${AWS_REGION}
    endpoint: ${AWS_URI}
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  sqs:
    queue:
      active-subscription: ${ACTIVE_SUBSCRIPTION_QUEUE}
      deactivate-subscription: ${DEACTIVATE_SUBSCRIPTION_QUEUE}

sns:
  topic:
    subscription-created: arn:aws:sns:us-east-1:000000000000:subscription-created-topic

stripe:
  api-key: ${STRIPE_SECRET_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}

subscription:
  service:
    client-id: ${SUBSCRIPTION_SERVICE_CLIENT_ID}
    client-secret: ${SUBSCRIPTION_SERVICE_SECRET}
