server:
  port: 0

spring:
  datasource:
    url: ${INVOICE_SERVICE_URL_DATABASE}
    username: ${INVOICE_USER}
    password: ${INVOICE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${SECRET_KEY}

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_ZONE_URL}
  instance:
    instance-id: ${spring.application.name}:${random.value}

aws:
  region: ${AWS_REGION}
  endpoint: ${AWS_URI}
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}

  sqs:
    queue:
      generate-invoice: ${GENERATE_NEW_INVOICE_QUEUE}
      invoice-created: ${INVOICE_CREATED_QUEUE}

  s3:
    bucket: ${AWS_S3_BUCKET}
    endpoint-override: ${AWS_URI}
    region: ${AWS_REGION}
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        url: ${OTLP_METRICS_EXPORT_URL}
        step: 10s
    logging:
      endpoint: ${OTLP_LOGGING_EXPORT_URL}
    tracing:
      endpoint: ${OTLP_TRACING_EXPORT_URL}
