server:
  port: 0

spring:
  datasource:
    url: ${SUBSCRIPTION_SERVICE_URL_DATABASE}
    username: ${BILLING_ENGINE_DB_USER}
    password: ${BILLING_ENGINE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${SECRET_KEY}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_ZONE_URL}
  instance:
    instance-id: ${spring.application.name}:${random.value}

security:
  jwt:
    secret-key: ${SECRET_KEY}

aws:
  region: ${AWS_REGION}
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}

  sqs:
    queue:
      active-subscription: ${ACTIVE_SUBSCRIPTION_QUEUE}
      deactivate-subscription: ${DEACTIVATE_SUBSCRIPTION_QUEUE}

sns:
  topic:
    subscription-created: ${SUBSCRIPTION_CREATED_TOPIC}

stripe:
  api-key: ${STRIPE_SECRET_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}

subscription:
  service:
    client-id: ${SUBSCRIPTION_SERVICE_CLIENT_ID}
    client-secret: ${SUBSCRIPTION_SERVICE_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        url: ${OTLP_METRICS_EXPORT_URL}
        step: 10s
    logging:
      endpoint: ${OTLP_LOGGING_EXPORT_URL}
    tracing:
      endpoint: ${OTLP_TRACING_EXPORT_URL}
