server:
  port: 0

spring:
  datasource:
    url: ${PAYMENT_SERVICE_URL_DATABASE}
    username: ${BILLING_ENGINE_DB_USER}
    password: ${BILLING_ENGINE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    aws:
      region:
        static: ${AWS_REGION}
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}

    config:
      discovery:
        enabled: true
        service-id: config-server

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${SECRET_KEY}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_ZONE_URL}
  instance:
    instance-id: ${spring.application.name}:${random.value}

security:
  jwt:
    secret-key: ${SECRET_KEY}

aws:
  region: ${AWS_REGION}
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}

  sqs:
    queue:
      process-payment: ${PROCESS_PAYMENT_QUEUE}
      payment-processing-dlq: ${PAYMENT_PROCESSING_DLQ}
  sns:
    topic:
      payment-approved: ${PAYMENT_APPROVED_TOPIC}
      payment-failed: ${PAYMENT_FAILED_TOPIC}

stripe:
  api-key: ${STRIPE_SECRET_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SIGN}

resilience4j:
  retry:
    instances:
      stripe:
        retry-exceptions:
          - com.stripe.exception.ApiConnectionException
          - com.stripe.exception.ApiException
          - com.stripe.exception.RateLimitException
        max-attempts: 4
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        wait-duration: 1

  circuitbreaker:
    instances:
      stripe:
        record-exceptions:
          - com.stripe.exception.ApiConnectionException
          - com.stripe.exception.ApiException
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        url: ${OTLP_METRICS_EXPORT_URL}
        step: 10s
    logging:
      endpoint: ${OTLP_LOGGING_EXPORT_URL}
    tracing:
      endpoint: ${OTLP_TRACING_EXPORT_URL}